### ISSUE TITLE
Compatibility with other laptops

### ISSUE THREAD

**Issue by Enelar** [bijection/sistine#3]
I wanted to fork and try it out on my old  Acer V3 371 (i5, 32Gb Ram, 1TB ssd), but im not sure if it going to work. What if i took a pen and and draw apple, would your code consider it as a macbook? Is my four year specs enough to run this code?

**Comment by anishathalye** [comment]
In the demo video, we’re running it on a 2013 MacBook Pro, so I’m pretty sure it’ll run fine on your computer.

**Comment by lengstrom** [comment]
I think all the APIs we use for clicking etc are Mac specific - so you'd have to rewrite most of `simulate.py` at the very least.

**Comment by thiswillbeyourgithub** [comment]
I think it would be incredible to have Sistine work on e-ink screens with single board computers like the raspberry pi. It would definitely put this project under the spotlight :)
